### ISSUE TITLE
Where is the dockerfile?

### ISSUE THREAD

**Issue by pascalandy** [geerlingguy/fathom-container#1]
Hi,

I was trying to run Fathom from the official docker image but it's not running:

```
docker run -d -p 8080:8080 usefathom/fathom:latest
```

I tried your image and it's working.

```
docker run -d -p 9000:9000 geerlingguy/fathom:latest
```

May I ask where is your Dockerfile? I understand ansible builds it but I just not understand how it's happening without the Dockerfile :-p

I would really appreciate your help!

Cheers!

**Comment by geerlingguy** [comment]
@pascalandy - In this case, Ansible is my Dockerfile :)

https://github.com/geerlingguy/fathom-container/blob/master/main.yml#L26-L58

You technically don't need Dockerfiles to build docker images. In the Ansible playbook, it creates a container, then does stuff inside the container, then commits the container and tags it as an image.

That way I can build flexible roles and stuff with Ansible to build my Docker images the same way I build my other infrastructure instead of locking in a bunch of complicated bash one-liners in a Dockerfile.

**Comment by pascalandy** [comment]
Wow, I was not aware you could do this!

Thanks for sharing :)
